### ISSUE TITLE
TEEZOS WHAT THE ####

### ISSUE THREAD

**Issue by bloxstrapper** [GoingCrazyDude/fastflags-collection#2]
github jumpscare

![image](https://github.com/GoingCrazyDude/fastflags-collection/assets/98201320/c65bfd70-bd9a-4ea1-9a2a-8a741e1e5c9f)

???

YOU COPY ME

![exposed](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/d69ed5eb-0731-45fb-8664-eeff27a0c83f)

Heres mine:
![mine](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/760d1f6f-a801-477b-984c-45c651c019d2)

WHAT THE ####?
![cmon man](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/a9dcc709-825f-4070-81d1-359f593de284)

amogus
mine:
![image](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/051725e0-3a21-4bfa-b26e-28afc5cade3e)
yours:
![image](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/b8d229d8-676e-4d2c-b042-b27e6dc96306)

n0o0bie stealer
![image](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/1e23cc56-f14d-41eb-a281-5c452fe44e07)
![image](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/c5a303e0-cd21-44d7-82ee-9e8bf6e633bb)

i think mine should be here or i will report
![image](https://github.com/GoingCrazyDude/fastflags-collection/assets/130872826/91ed93a1-96c5-46f4-82d9-e17527cb4615)

**Comment by GoingCrazyDude** [comment]
stop scizo posting retard

**Comment by bloxstrapper** [comment]
im reporting you

**Comment by bloxstrapper** [comment]
just accept my list is better 🤑🤑
